codecov:
  branch: main
  notify:
    after_n_builds: 2
comment: false

coverage:
  status:
    project:
      default:
        target: '75'
    patch:
      default:
        target: '50'
        informational: true

github_checks:
    annotations: false